//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ord_Detail
    {
        public int Id { get; set; }
        public int Id_Ord { get; set; }
        public int Id_Product { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> totalDetail { get; set; }
    
        public virtual Ord Ord { get; set; }
        public virtual Product Product { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
